// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MIMONATCH/xysbtnProfileGetter/internal/biz"
	"github.com/MIMONATCH/xysbtnProfileGetter/internal/config"
	"github.com/MIMONATCH/xysbtnProfileGetter/internal/data"
)

// Injectors from wire.go:

func InitApp(configFile2 string) (*biz.App, error) {
	profileConfig, err := config.NewConfig(configFile2)
	if err != nil {
		return nil, err
	}
	compress := biz.NewCompress()
	profile := biz.NewProfile(profileConfig)
	download := biz.NewDownload(profileConfig, compress, profile)
	repo := data.NewRepo()
	app := biz.NewApp(download, repo)
	return app, nil
}
