name: xysbtn-profileGetter-go

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * */1 * *"
  workflow_dispatch:

jobs:
  buildAndRunAndDeploy:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: install dependency
        run: brew install webp
      - name: build
        run: |
          go mod tidy
          cd cmd
          go build -o ./app
      - name: go run
        run: |
          cd cmd
          ./app
        env:
          CGO_CFLAGS: -I/opt/homebrew/include
          CGO_LDFLAGS: -L/opt/homebrew/lib
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.xysbtndeploy }}
          ARGS: "-rltgoDzvO"
          SOURCE: "webp/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: ""