name: xysbtn-profileGetter-go

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * */7 * *"
  workflow_dispatch:

jobs:
  buildAndRunAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: install dependency
        run: sudo apt install libjpeg-dev libpng-dev libtiff-dev libgif-dev make
      - name: make webplib
        run: |
          wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.4.tar.gz
          tar xvzf libwebp-1.2.4.tar.gz
          cd libwebp-1.2.4
          ./configure
          make
          sudo make install
      - name: build
        run: |
          go mod tidy
          cd cmd
          go build -o ./app
      - name: go run
        run: |
          ./app
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.xysbtndeploy }}
          ARGS: "-rltgoDzvO"
          SOURCE: "webp/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: ""